server:
  port: 8097
spring:
  application:
    name: spring-cloud-getaway
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: getaway-service
          uri: https://github.com/
          predicates:
              - Path=/zlh-star
      discovery:
        locator:
          enabled: true
logging:
  level:
   org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
