server:
  port: 8087
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
        username: nacos
        password: nacos
feign:
  hystrix:
    enabled: true
