server:
  port: 8092
spring:
  application:
    name: client-server2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    config:
      server:
        git:
          uri: https://github.com/zlh-star/test
          default-label: main
          search-paths: springcloud-config
          username: zlh-star
          password: "@zlh199806"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
