server:
  port: 8086
spring:
  application:
    name: provider
  security:
    user:
      name: admin
      password: admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
