server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
        username: nacos
        password: nacos
    config:
      server:
        git:
          uri: https://github.com/zlh-star/test
          default-label: main
          search-paths: springcloud-config
          username: zlh-star
          password: "@zlh199806"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

