server:
  port: 8098
spring:
  data:
    mongodb:
#      username:
#      password:
      port: 27017
      host: localhost
      database: zlh
  application:
    name: spring-swagger
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always